{% set name = "geomeTRIC" %}
{% set version = "1.0.1" %}
{% set sha256 = "9f57b58fa7551c49af2b6e9c18e51b867d3b0d5e9f78890423ffdcc9f66543a3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/leeping/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - patches/windows-rdre.patch

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - geometric-optimize = geometric.optimize:main

requirements:
  host:
    - python >=3.7
    - setuptools
    - pip
  run:
    - python >=3.7
    - setuptools
    - {{ pin_compatible('numpy', lower_bound='1.18') }}
    - networkx
    - six

test:
  imports:
    - geometric
  requires:
    - pytest
    - rdkit
    - openmm
    - ase
    - xtb-python
  commands:
    - $PYTHON -m pytest --pyargs geometric -v -k json

about:
  home: http://github.com/leeping/geomeTRIC/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Molecular geometry optimizer in the TRIC coordinate system.
  dev_url: http://github.com/leeping/geomeTRIC/

extra:
  recipe-maintainers:
    - leeping
    - dgasmith
    - yudongqiu
