{% set name = "geomeTRIC" %}
{% set version = "0.9.2" %}
{% set sha256 = "0a2993c0eb4f7ed77017046c9968cfb4585c70bbad190e0fc750b20254b7728a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/leeping/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - geometric-optimize = geometric.optimize:main

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - {{ pin_compatible('numpy', lower_bound='1.11') }}
    - python
    - networkx
    - six

test:
  imports:
    - pytest
    - geometric
  requires:
    - pytest
  commands:
    - py.test --pyargs geometric

about:
  home: http://github.com/leeping/geomeTRIC/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Molecular geometry optimizer in the TRIC coordinate system.'

  dev_url: http://github.com/leeping/geomeTRIC/

extra:
  recipe-maintainers:
    - leeping
    - dgasmith
    - yudongqiu
