{% set name = "geomeTRIC" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/leeping/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 7a6452769d83ff5a6461f06c2dabd2b63d9bd756b1c820dbe48f9aa623af287d

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - geometric-optimize = geometric.optimize:main

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - setuptools
    - numpy
    - networkx
    - six

test:
  imports:
    - geometric
  requires:
    - pytest
    - rdkit
    - openmm
    - ase
    - xtb-python
    - python {{ python_min }}
  commands:
    - $PYTHON -m pytest --pyargs geometric -v -k json

about:
  home: http://github.com/leeping/geomeTRIC/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Molecular geometry optimizer in the TRIC coordinate system.'
  dev_url: http://github.com/leeping/geomeTRIC/

extra:
  recipe-maintainers:
    - leeping
    - dgasmith
    - yudongqiu
