travis:
  secure:
    BINSTAR_TOKEN: owOgPSZxpvrKnuhA2ybMVPXnLtn3TXerME4JBJhzlBdWHWf2w1/1yjrX4gdeF8YOXeVAtiQspAos0YTwqLmHBAs5TYhmY6WnZPvbeayBOBGpJpXAStGnM/bD4G6maAJ8HUtpK/L4udr/GSP/NfWivw6v1Ke5/gBKscMFYog7iDXB68dJ+TJaWMFAKO5bkqMSXnKknOW+GPiKpHds9qPo30iZ2eh3ZNrrBLithOhvFX5CfMOf/Wh1WjgDdAVjewaMMqnO4Y11GvIeXc0AP0B4BtxuQ0+BkWY3GRenDTdpZnYf+cZJH5lPk0kgFFtk3LjBagmF6I/9EtkCVNWWGp9W0miClclmEhWqH8lLZP+fjsmUAEf7t5ZAaQf9HTzlrlYAK2FF1dy6sQGavn1vLxoEpOAuSWT9wunkQiB5Tfcc0RrEmh38dkHfsqyNlH41R4sWPIS870prRiFipKLyHj1TmhCVzIqPRxJH+vPRqi3zmoJJ6JNk3v+AgHEWJisSzy6utZXW7OTmAe6zy9b0UOUFf4/vctG9Kgnq+Eg45NvaheWm8PD+JTOVfbrjWhKJC0f8OvYTGNeHb4vHqqBlG0ayhq6FRthl/97EXF7tqPL7Ej2/bFZM+rs8brz+FRBp8z8hD65zIONxdDx6tKXrZx2j1uWg6P0+oA61McMMe5UddKs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
